### ISSUE TITLE
Android/iOS automated tests do not support Stage experiments

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/klaatu#162]
### Workflow commands Android:
 - Branch: ['control']
 - Experiment Slug: ppop-androidish-test
 - Firefox Version: ['130.0']
 - Additional Arguments; --experiment-server stage

### Workflow commands iOS:
 - Branch: ['control']
 - Experiment Slug: ppop-iosish-test
 - Firefox Version: ['130.0']
 - Additional Arguments; --experiment-server stage
 
Running the mobile tests with or without --experiment-server stage fails for Stage experiments.
Android Test Run with report: https://github.com/mozilla/klaatu/actions/runs/10807865020
iOS Test Run with report: https://github.com/mozilla/klaatu/actions/runs/10807873595

**Comment by b4handjr** [comment]
Fixed in #166 and #164
